import type { LevelDefinition } from './types.ts';

export const LEVELS: readonly LevelDefinition[] = [
  {
    id: 'level-1',
    name: 'LEVEL 1',
    subtitle: 'TEST CHAMBER',
    hint: 'Get close. Pick a side. Let the blast do the jumping.',
    intent: {
      primaryRoute: 'START -> B1 -> middle deck -> B2 -> upper deck -> B3 -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Teach proximity and side choice with a broad first ascent.' },
        { bomb: 'B2', job: 'Continue upward after the first safe landing.' },
        { bomb: 'B3', job: 'Confirm the learned blast-to-exit pattern.' },
      ],
      landingWindows: [{ target: 'middle and upper decks', kind: 'wide', description: 'Correct blast placement should land safely.' }],
      timingWindows: [{ target: 'all charges', kind: 'open', description: 'The player may wait and inspect each setup.' }],
      recovery: { kind: 'safe', description: 'The floor and broad decks preserve most near-misses.' },
      masteryShortcut: null,
      newConcept: 'A nearby industrial blast substitutes for a missing jump function.',
      recombinedSkills: [],
      targetFirstClearSeconds: { min: 35, max: 90 },
    },
    validation: {},
    start: { x: 92, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 960, h: 50 },
      { x: 396, y: 402, w: 224, h: 22 },
      { x: 704, y: 238, w: 210, h: 22 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [
      { x: 304, y: 532, delay: 0, label: 'B1' },
      { x: 535, y: 384, delay: 1.7, label: 'B2' },
      { x: 754, y: 220, delay: 3.2, label: 'B3' },
    ],
    exit: { x: 822, y: 174, w: 54, h: 64 },
  },
  {
    id: 'level-2',
    name: 'LEVEL 2',
    subtitle: 'TRAJECTORY TEST',
    hint: 'Choose your launch line. Steer through the opening while airborne.',
    intent: {
      primaryRoute: 'START -> choose B1 side -> steer through OPENING -> EXIT deck',
      launchJobs: [{ bomb: 'B1', job: 'Launch through a visible horizontal opening.' }],
      landingWindows: [{ target: 'right deck', kind: 'wide', description: 'The opening is the test; landing is forgiving.' }],
      timingWindows: [{ target: 'B1', kind: 'open', description: 'The player can choose a launch line before commitment.' }],
      recovery: { kind: 'safe', description: 'A failed line returns to the continuous lower floor.' },
      masteryShortcut: null,
      newConcept: 'Imperfect midair steering changes a blast trajectory.',
      recombinedSkills: ['blast proximity', 'side choice'],
      targetFirstClearSeconds: { min: 45, max: 110 },
    },
    validation: {},
    start: { x: 92, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 960, h: 50 },
      { x: 18, y: 330, w: 477, h: 28 },
      { x: 610, y: 330, w: 332, h: 28 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 460, y: 532, delay: 0, label: 'B1' }],
    exit: { x: 838, y: 266, w: 54, h: 64 },
    opening: { x: 495, y: 330, w: 115, h: 28 },
  },
  {
    id: 'level-3',
    name: 'LEVEL 3',
    subtitle: 'TIGHT POCKET',
    hint: 'Thread the slot. Brake in midair. Land in the pocket.',
    intent: {
      primaryRoute: 'START -> B1 -> brake through slot -> pocket -> EXIT',
      launchJobs: [{ bomb: 'B1', job: 'Create enough ascent while preserving room to brake.' }],
      landingWindows: [{ target: 'exit pocket', kind: 'tight', description: 'Air braking is the explicit precision lesson.' }],
      timingWindows: [{ target: 'B1', kind: 'open', description: 'Setup is repeatable; execution carries the challenge.' }],
      recovery: { kind: 'safe', description: 'Underpowered attempts return to lower geometry.' },
      masteryShortcut: null,
      newConcept: 'Counter-steering brakes horizontal momentum before landing.',
      recombinedSkills: ['launch line', 'midair steering'],
      targetFirstClearSeconds: { min: 55, max: 140 },
    },
    validation: {},
    start: { x: 92, y: 464 },
    platforms: [
      { x: 0, y: 500, w: 390, h: 22 },
      { x: 18, y: 300, w: 372, h: 22 },
      { x: 490, y: 300, w: 30, h: 22 },
      { x: 560, y: 360, w: 110, h: 22 },
      { x: 520, y: 170, w: 180, h: 22 },
      { x: 700, y: 170, w: 28, h: 330 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 350, y: 482, delay: 0, label: 'B1' }],
    exit: { x: 588, y: 296, w: 54, h: 64 },
    opening: { x: 390, y: 300, w: 100, h: 22 },
  },
  {
    id: 'level-4',
    name: 'LEVEL 4',
    subtitle: 'AIR COMBO',
    hint: 'First blast starts the chain. Meet the floating bomb before you touch down.',
    intent: {
      primaryRoute: 'START -> B1 -> airborne B2 -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Start an arc aimed at the floating relay.' },
        { bomb: 'B2', job: 'Continue the ascent without a landing reset.' },
      ],
      landingWindows: [{ target: 'exit deck', kind: 'wide', description: 'Completing the air chain should produce a readable landing.' }],
      timingWindows: [{ target: 'B2', kind: 'commit', description: 'The relay must be met before touching down.' }],
      recovery: { kind: 'safe', description: 'Most misses return to the broad floor for another cycle.' },
      masteryShortcut: null,
      newConcept: 'Two blasts can form one uninterrupted airborne chain.',
      recombinedSkills: ['launch line', 'midair steering'],
      targetFirstClearSeconds: { min: 60, max: 150 },
    },
    validation: { requiredBlastHits: ['B1', 'B2'], minimumAirCombo: 2 },
    start: { x: 92, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 960, h: 50 },
      { x: 18, y: 350, w: 432, h: 22 },
      { x: 580, y: 350, w: 140, h: 22 },
      { x: 750, y: 190, w: 192, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [
      { x: 400, y: 532, delay: 0, label: 'B1' },
      { x: 625, y: 260, delay: 0.7, label: 'B2', floating: true },
    ],
    exit: { x: 842, y: 126, w: 54, h: 64 },
    opening: { x: 450, y: 350, w: 130, h: 22 },
  },
  {
    id: 'level-5',
    name: 'LEVEL 5',
    subtitle: 'SYNTHESIS I',
    hint: 'Find the line between the void and the teeth.',
    intent: {
      primaryRoute: 'START -> B1 -> safe middle platform -> B2 -> right deck -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Cross the first pit while avoiding hanging teeth.' },
        { bomb: 'B2', job: 'Lift from the middle route to the exit deck.' },
      ],
      landingWindows: [{ target: 'middle platform', kind: 'medium', description: 'A correct line has margin but hazards punish drift.' }],
      timingWindows: [{ target: 'B2', kind: 'commit', description: 'The second charge rewards continuing the route.' }],
      recovery: { kind: 'costly', description: 'Some short attempts survive; pit or teeth punish the wrong line.' },
      masteryShortcut: null,
      newConcept: 'Hazards make route choice consequential.',
      recombinedSkills: ['air braking', 'air chain'],
      targetFirstClearSeconds: { min: 75, max: 180 },
    },
    validation: {},
    start: { x: 92, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 300, h: 50 },
      { x: 370, y: 500, w: 160, h: 22 },
      { x: 600, y: 360, w: 342, h: 22 },
      { x: 300, y: 200, w: 130, h: 20 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [
      { x: 190, y: 532, delay: 0, label: 'B1' },
      { x: 455, y: 470, delay: 0.75, label: 'B2', floating: true },
    ],
    exit: { x: 842, y: 296, w: 54, h: 64 },
    spikes: [{ x: 300, y: 220, w: 130, h: 65 }],
    pit: { x: 300, y: 500, w: 300, h: 100 },
  },
  {
    id: 'level-6',
    name: 'LEVEL 6',
    subtitle: 'INTERCEPT',
    hint: 'Launch for where the platform will be. Close blast, fast exit. Wide blast, safer ride.',
    intent: {
      primaryRoute: 'START -> B1 -> intercept moving platform -> right deck -> EXIT',
      launchJobs: [{ bomb: 'B1', job: 'Launch toward a future moving-platform position.' }],
      landingWindows: [{ target: 'moving platform', kind: 'medium', description: 'Prediction matters more than narrow geometry.' }],
      timingWindows: [{ target: 'moving platform', kind: 'intercept', description: 'Aim for the platform future, not its current position.' }],
      recovery: { kind: 'fatal', description: 'Missing the platform falls into the deep pit.' },
      masteryShortcut: 'A close, powerful launch can reach the exit deck before a long ride.',
      newConcept: 'Intercept a moving future state.',
      recombinedSkills: ['blast strength by proximity', 'air steering'],
      targetFirstClearSeconds: { min: 80, max: 200 },
    },
    validation: {},
    start: { x: 92, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 330, h: 50 },
      { x: 840, y: 450, w: 102, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 250, y: 532, delay: -2.8, label: 'B1' }],
    exit: { x: 876, y: 386, w: 54, h: 64 },
    pit: { x: 330, y: 450, w: 510, h: 150 },
    movingPlatform: {
      fromX: 440,
      toX: 700,
      y: 450,
      w: 140,
      h: 22,
      speed: 140,
      phase: 2.14,
    },
  },
  {
    id: 'level-7',
    name: 'LEVEL 7',
    subtitle: 'RETURN ARC',
    hint: 'Clear the hanging teeth after B1. Return left with B2, then launch from the left side of B3.',
    intent: {
      primaryRoute: 'START -> B1 -> lower deck -> B2 return left -> upper platform -> left side of B3 -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Clear hanging teeth and commit to the lower deck.' },
        { bomb: 'B2', job: 'Reverse traversal direction into the return arc.' },
        { bomb: 'B3', job: 'Launch from its left side into the upper-left exit.' },
      ],
      landingWindows: [
        { target: 'lower deck', kind: 'wide', description: 'The route decision, not landing precision, is primary.' },
        { target: 'upper platform', kind: 'medium', description: 'Catches imperfect return arcs.' },
      ],
      timingWindows: [{ target: 'B2', kind: 'expiring', description: 'Reach the lower deck before the useful B2 cycle passes.' }],
      recovery: { kind: 'recoverable', description: 'The upper platform rescues some imperfect return arcs.' },
      masteryShortcut: 'A clean B1 arc may reach the exit directly, but should be uncommon for first-time players.',
      newConcept: 'A blast reverses the route into a return arc.',
      recombinedSkills: ['blast timing', 'air steering', 'route hierarchy'],
      targetFirstClearSeconds: { min: 100, max: 240 },
    },
    validation: {},
    start: { x: 92, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 330, h: 50 },
      { x: 40, y: 140, w: 210, h: 22 },
      { x: 250, y: 300, w: 250, h: 22 },
      { x: 400, y: 470, w: 390, h: 22 },
      { x: 360, y: 70, w: 140, h: 20 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [
      { x: 250, y: 532, delay: -2.5, label: 'B1' },
      { x: 680, y: 452, delay: -0.2, label: 'B2' },
      { x: 400, y: 282, delay: 1.9, label: 'B3' },
    ],
    exit: { x: 120, y: 76, w: 54, h: 64 },
    spikes: [
      { x: 250, y: 322, w: 70, h: 58 },
      { x: 360, y: 90, w: 140, h: 70 },
    ],
    pit: { x: 330, y: 470, w: 630, h: 130 },
  },
  {
    id: 'level-8',
    name: 'LEVEL 8',
    subtitle: 'AIR SLALOM',
    hint: 'Hold right into the launch post. B1 lifts off, then flip direction on every blast: left, right, left, right.',
    intent: {
      primaryRoute: 'START -> launch post -> B1 -> B2 -> B3 -> B4 -> B5 -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Lift from the pinned launch position.' },
        { bomb: 'B2', job: 'Knock left and re-lift.' },
        { bomb: 'B3', job: 'Knock right and re-lift.' },
        { bomb: 'B4', job: 'Knock left and re-lift.' },
        { bomb: 'B5', job: 'Knock right into the combo-gated exit.' },
      ],
      landingWindows: [{ target: 'airborne exit', kind: 'none', description: 'There is no intermediate landing reset.' }],
      timingWindows: [{ target: 'B1–B5 relay', kind: 'expiring', description: 'The five fuse events form one committed airborne sequence.' }],
      recovery: { kind: 'fatal', description: 'A missed relay drops into the pit; the cycle restarts quickly.' },
      masteryShortcut: null,
      newConcept: 'A fully airborne five-blast slalom with load-bearing steering reversals.',
      recombinedSkills: ['air steering', 'air chaining', 'direction reversal'],
      targetFirstClearSeconds: { min: 120, max: 300 },
    },
    validation: {
      requiredBlastHits: ['B1', 'B2', 'B3', 'B4', 'B5'],
      minimumAirCombo: 5,
      simplePoliciesMustFail: ['hold-left', 'neutral', 'hold-right'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 30, samples: 100, minimumClearRate: 0.6 },
        { jitterMilliseconds: 80, samples: 100, minimumClearRate: 0.25 },
      ],
    },
    start: { x: 92, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 484, h: 50 },
      { x: 470, y: 508, w: 14, h: 42 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [
      { x: 410, y: 532, delay: -2.4, label: 'B1' },
      { x: 590, y: 452, delay: -1.9, label: 'B2', floating: true },
      { x: 445, y: 346, delay: -1.5, label: 'B3', floating: true },
      { x: 656, y: 213, delay: -1.1, label: 'B4', floating: true },
      { x: 491, y: 135, delay: -0.7, label: 'B5', floating: true },
    ],
    exit: { x: 550, y: 97, w: 86, h: 70 },
    pit: { x: 484, y: 500, w: 476, h: 100 },
    requiredCombo: 5,
  },
  {
    id: 'level-9',
    name: 'LEVEL 9',
    subtitle: 'COLD START',
    hint: 'Pass through coolant. Carry the blue state across the hot plate, then use the charge.',
    intent: {
      primaryRoute: 'START -> coolant source -> cool HOT PLATE -> cross safely -> pass B1 -> blast into upper shaft -> steer left -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Launch from the right wall up the open shaft, then allow a leftward landing on the exit deck.' },
      ],
      landingWindows: [{ target: 'upper exit deck', kind: 'wide', description: 'Cold is the new lesson; the returning landing is intentionally broad.' }],
      timingWindows: [
        { target: 'cooled hot plate', kind: 'open', description: 'The coolant source is unavoidable and refreshable before crossing.' },
        { target: 'B1 launch', kind: 'commit', description: 'Reach the right launch wall for the prepared blast, then steer left above the deck.' },
      ],
      recovery: { kind: 'safe', description: 'The cooled plate and right floor are stable; incorrect neutral contact resets immediately and readably.' },
      masteryShortcut: null,
      newConcept: 'A temporary cold state makes one visibly overheated factory surface safe.',
      recombinedSkills: ['blast proximity', 'midair steering'],
      targetFirstClearSeconds: { min: 55, max: 140 },
    },
    validation: {
      requiredBlastHits: ['B1'],
      requiredInteractions: ['hot-plate-cooling'],
      requiredStates: ['cold'],
      simplePoliciesMustFail: ['hold-left', 'neutral', 'hold-right'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 100, samples: 100, minimumClearRate: 0.8 },
      ],
    },
    start: { x: 82, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 360, h: 50 },
      { x: 360, y: 550, w: 270, h: 50 },
      { x: 630, y: 550, w: 312, h: 50 },
      { x: 620, y: 350, w: 250, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 900, y: 532, delay: -1.5, label: 'B1' }],
    exit: { x: 700, y: 286, w: 64, h: 64 },
    traversalStateSources: [
      {
        id: 'coolant-gate',
        rect: { x: 150, y: 500, w: 92, h: 50 },
        grants: 'cold',
        durationSeconds: 7,
      },
    ],
    traversalInteractions: [
      {
        id: 'hot-plate-cooling',
        rect: { x: 344, y: 500, w: 302, h: 54 },
        kind: 'cool-surface',
        accepts: ['cold'],
        activeSeconds: 5,
      },
    ],
    hotSurfaces: [
      {
        id: 'hot-plate',
        rect: { x: 360, y: 542, w: 270, h: 12 },
        cooledByInteractionId: 'hot-plate-cooling',
      },
    ],
  },
  {
    id: 'level-10',
    name: 'LEVEL 10',
    subtitle: 'CONDENSATE GAP',
    hint: 'Carry coolant to the dripping edge. Cross while the frozen path holds, then use the charge.',
    intent: {
      primaryRoute: 'START -> coolant source -> freeze condensate -> cross temporary ice -> pass B1 -> blast into upper shaft -> steer left -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Launch from the right wall up the open shaft, then allow a leftward landing on the exit deck.' },
      ],
      landingWindows: [
        { target: 'frozen condensate bridge', kind: 'wide', description: 'The new temporary surface spans the whole water gap.' },
        { target: 'upper exit deck', kind: 'wide', description: 'The familiar blast landing remains forgiving while freezing is learned.' },
      ],
      timingWindows: [
        { target: 'frozen bridge', kind: 'expiring', description: 'The bridge lasts long enough for a readable crossing and then thaws deterministically.' },
        { target: 'B1 launch', kind: 'commit', description: 'Reach the far launch wall for the prepared blast, then steer left above the deck.' },
      ],
      recovery: { kind: 'fatal', description: 'A short crossing enters the water; the far bank is stable once reached.' },
      masteryShortcut: null,
      newConcept: 'Cold freezes one water span into a temporary collision surface.',
      recombinedSkills: ['cold acquisition', 'blast proximity', 'midair steering'],
      targetFirstClearSeconds: { min: 65, max: 150 },
    },
    validation: {
      requiredBlastHits: ['B1'],
      requiredInteractions: ['condensate-freeze'],
      requiredStates: ['cold'],
      simplePoliciesMustFail: ['hold-left', 'neutral', 'hold-right'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 100, samples: 100, minimumClearRate: 0.8 },
      ],
    },
    start: { x: 82, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 320, h: 50 },
      { x: 650, y: 550, w: 292, h: 50 },
      { x: 620, y: 350, w: 250, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 900, y: 532, delay: -1.5, label: 'B1' }],
    exit: { x: 700, y: 286, w: 64, h: 64 },
    traversalStateSources: [
      {
        id: 'coolant-gate',
        rect: { x: 130, y: 500, w: 92, h: 50 },
        grants: 'cold',
        durationSeconds: 7,
      },
    ],
    traversalInteractions: [
      {
        id: 'condensate-freeze',
        rect: { x: 292, y: 494, w: 56, h: 60 },
        kind: 'freeze-water',
        accepts: ['cold'],
        activeSeconds: 4.8,
        resultRect: { x: 320, y: 550, w: 330, h: 18 },
      },
    ],
    waterHazards: [
      {
        id: 'condensate-pool',
        rect: { x: 320, y: 550, w: 330, h: 50 },
        frozenByInteractionId: 'condensate-freeze',
      },
    ],
  },
  {
    id: 'level-11',
    name: 'LEVEL 11',
    subtitle: 'COLD LOCK',
    hint: 'Chill the carriage control. Launch while the transfer deck is held at the blue dock.',
    intent: {
      primaryRoute: 'START -> coolant source -> stabilize transfer carriage -> B1 -> locked carriage -> right inspection deck -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Launch from the left floor onto the carriage held at its marked dock.' },
      ],
      landingWindows: [
        { target: 'locked transfer carriage', kind: 'wide', description: 'The fixed carriage and adjoining inspection deck form a broad landing region.' },
      ],
      timingWindows: [
        { target: 'carriage lock', kind: 'expiring', description: 'The cold lock lasts through the prepared launch and landing, then releases the normal cycle.' },
        { target: 'B1 launch', kind: 'commit', description: 'The launch post fixes the takeoff position for the prepared blast.' },
      ],
      recovery: { kind: 'fatal', description: 'Missing the carriage falls into the machinery pit; the start floor is safe before launch.' },
      masteryShortcut: null,
      newConcept: 'Cold temporarily fixes a moving transfer carriage at its marked dock.',
      recombinedSkills: ['cold acquisition', 'blast proximity', 'midair steering'],
      targetFirstClearSeconds: { min: 70, max: 165 },
    },
    validation: {
      requiredBlastHits: ['B1'],
      requiredInteractions: ['carriage-lock'],
      requiredStates: ['cold'],
      simplePoliciesMustFail: ['hold-left', 'neutral'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 100, samples: 100, minimumClearRate: 0.75 },
      ],
    },
    start: { x: 82, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 330, h: 50 },
      { x: 316, y: 508, w: 14, h: 42 },
      { x: 700, y: 450, w: 242, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 250, y: 532, delay: -2.5, label: 'B1' }],
    exit: { x: 716, y: 386, w: 64, h: 64 },
    pit: { x: 330, y: 450, w: 370, h: 150 },
    movingPlatform: {
      fromX: 350,
      toX: 700,
      y: 450,
      w: 370,
      h: 22,
      speed: 160,
      phase: 0.4,
      stabilizedByInteractionId: 'carriage-lock',
      stabilizedX: 330,
    },
    traversalStateSources: [
      {
        id: 'coolant-gate',
        rect: { x: 100, y: 500, w: 82, h: 50 },
        grants: 'cold',
        durationSeconds: 7,
      },
    ],
    traversalInteractions: [
      {
        id: 'carriage-lock',
        rect: { x: 190, y: 492, w: 82, h: 62 },
        kind: 'stabilize-machine',
        accepts: ['cold'],
        activeSeconds: 5.5,
      },
    ],
  },
];
