import type { LevelDefinition } from './types.ts';

export const LEVELS: readonly LevelDefinition[] = [
  {
    id: 'level-1',
    name: 'LEVEL 1',
    subtitle: 'TEST CHAMBER',
    hint: 'Get close. Pick a side. Let the blast do the jumping.',
    intent: {
      primaryRoute: 'START -> B1 -> middle deck -> B2 -> upper deck -> B3 -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Teach proximity and side choice with a broad first ascent.' },
        { bomb: 'B2', job: 'Continue upward after the first safe landing.' },
        { bomb: 'B3', job: 'Confirm the learned blast-to-exit pattern.' },
      ],
      landingWindows: [{ target: 'middle and upper decks', kind: 'wide', description: 'Correct blast placement should land safely.' }],
      timingWindows: [{ target: 'all charges', kind: 'open', description: 'The player may wait and inspect each setup.' }],
      recovery: { kind: 'safe', description: 'The floor and broad decks preserve most near-misses.' },
      masteryShortcut: null,
      newConcept: 'A nearby industrial blast substitutes for a missing jump function.',
      recombinedSkills: [],
      targetFirstClearSeconds: { min: 35, max: 90 },
    },
    validation: {},
    start: { x: 92, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 960, h: 50 },
      { x: 396, y: 402, w: 224, h: 22 },
      { x: 704, y: 238, w: 210, h: 22 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [
      { x: 304, y: 532, delay: 0, label: 'B1' },
      { x: 535, y: 384, delay: 1.7, label: 'B2' },
      { x: 754, y: 220, delay: 3.2, label: 'B3' },
    ],
    exit: { x: 822, y: 174, w: 54, h: 64 },
  },
  {
    id: 'level-2',
    name: 'LEVEL 2',
    subtitle: 'TRAJECTORY TEST',
    hint: 'Choose your launch line. Steer through the opening while airborne.',
    intent: {
      primaryRoute: 'START -> choose B1 side -> steer through OPENING -> EXIT deck',
      launchJobs: [{ bomb: 'B1', job: 'Launch through a visible horizontal opening.' }],
      landingWindows: [{ target: 'right deck', kind: 'wide', description: 'The opening is the test; landing is forgiving.' }],
      timingWindows: [{ target: 'B1', kind: 'open', description: 'The player can choose a launch line before commitment.' }],
      recovery: { kind: 'safe', description: 'A failed line returns to the continuous lower floor.' },
      masteryShortcut: null,
      newConcept: 'Imperfect midair steering changes a blast trajectory.',
      recombinedSkills: ['blast proximity', 'side choice'],
      targetFirstClearSeconds: { min: 45, max: 110 },
    },
    validation: {},
    start: { x: 92, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 960, h: 50 },
      { x: 18, y: 330, w: 477, h: 28 },
      { x: 610, y: 330, w: 332, h: 28 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 460, y: 532, delay: 0, label: 'B1' }],
    exit: { x: 838, y: 266, w: 54, h: 64 },
    opening: { x: 495, y: 330, w: 115, h: 28 },
  },
  {
    id: 'level-3',
    name: 'LEVEL 3',
    subtitle: 'TIGHT POCKET',
    hint: 'Thread the slot. Brake in midair. Land in the pocket.',
    intent: {
      primaryRoute: 'START -> B1 -> brake through slot -> pocket -> EXIT',
      launchJobs: [{ bomb: 'B1', job: 'Create enough ascent while preserving room to brake.' }],
      landingWindows: [{ target: 'exit pocket', kind: 'tight', description: 'Air braking is the explicit precision lesson.' }],
      timingWindows: [{ target: 'B1', kind: 'open', description: 'Setup is repeatable; execution carries the challenge.' }],
      recovery: { kind: 'safe', description: 'Underpowered attempts return to lower geometry.' },
      masteryShortcut: null,
      newConcept: 'Counter-steering brakes horizontal momentum before landing.',
      recombinedSkills: ['launch line', 'midair steering'],
      targetFirstClearSeconds: { min: 55, max: 140 },
    },
    validation: {},
    start: { x: 92, y: 464 },
    platforms: [
      { x: 0, y: 500, w: 390, h: 22 },
      { x: 18, y: 300, w: 372, h: 22 },
      { x: 490, y: 300, w: 30, h: 22 },
      { x: 560, y: 360, w: 110, h: 22 },
      { x: 520, y: 170, w: 180, h: 22 },
      { x: 700, y: 170, w: 28, h: 330 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 350, y: 482, delay: 0, label: 'B1' }],
    exit: { x: 588, y: 296, w: 54, h: 64 },
    opening: { x: 390, y: 300, w: 100, h: 22 },
  },
  {
    id: 'level-4',
    name: 'LEVEL 4',
    subtitle: 'AIR COMBO',
    hint: 'First blast starts the chain. Meet the floating bomb before you touch down.',
    intent: {
      primaryRoute: 'START -> B1 -> airborne B2 -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Start an arc aimed at the floating relay.' },
        { bomb: 'B2', job: 'Continue the ascent without a landing reset.' },
      ],
      landingWindows: [{ target: 'exit deck', kind: 'wide', description: 'Completing the air chain should produce a readable landing.' }],
      timingWindows: [{ target: 'B2', kind: 'commit', description: 'The relay must be met before touching down.' }],
      recovery: { kind: 'safe', description: 'Most misses return to the broad floor for another cycle.' },
      masteryShortcut: null,
      newConcept: 'Two blasts can form one uninterrupted airborne chain.',
      recombinedSkills: ['launch line', 'midair steering'],
      targetFirstClearSeconds: { min: 60, max: 150 },
    },
    validation: { requiredBlastHits: ['B1', 'B2'], minimumAirCombo: 2 },
    start: { x: 92, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 960, h: 50 },
      { x: 18, y: 350, w: 432, h: 22 },
      { x: 580, y: 350, w: 140, h: 22 },
      { x: 750, y: 190, w: 192, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [
      { x: 400, y: 532, delay: 0, label: 'B1' },
      { x: 625, y: 260, delay: 0.7, label: 'B2', floating: true },
    ],
    exit: { x: 842, y: 126, w: 54, h: 64 },
    opening: { x: 450, y: 350, w: 130, h: 22 },
  },
  {
    id: 'level-5',
    name: 'LEVEL 5',
    subtitle: 'SYNTHESIS I',
    hint: 'Find the line between the void and the teeth.',
    intent: {
      primaryRoute: 'START -> B1 -> safe middle platform -> B2 -> right deck -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Cross the first pit while avoiding hanging teeth.' },
        { bomb: 'B2', job: 'Lift from the middle route to the exit deck.' },
      ],
      landingWindows: [{ target: 'middle platform', kind: 'medium', description: 'A correct line has margin but hazards punish drift.' }],
      timingWindows: [{ target: 'B2', kind: 'commit', description: 'The second charge rewards continuing the route.' }],
      recovery: { kind: 'costly', description: 'Some short attempts survive; pit or teeth punish the wrong line.' },
      masteryShortcut: null,
      newConcept: 'Hazards make route choice consequential.',
      recombinedSkills: ['air braking', 'air chain'],
      targetFirstClearSeconds: { min: 75, max: 180 },
    },
    validation: {},
    start: { x: 92, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 300, h: 50 },
      { x: 370, y: 500, w: 160, h: 22 },
      { x: 600, y: 360, w: 342, h: 22 },
      { x: 300, y: 200, w: 130, h: 20 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [
      { x: 190, y: 532, delay: 0, label: 'B1' },
      { x: 455, y: 470, delay: 0.75, label: 'B2', floating: true },
    ],
    exit: { x: 842, y: 296, w: 54, h: 64 },
    spikes: [{ x: 300, y: 220, w: 130, h: 65 }],
    pit: { x: 300, y: 500, w: 300, h: 100 },
  },
  {
    id: 'level-6',
    name: 'LEVEL 6',
    subtitle: 'INTERCEPT',
    hint: 'Launch for where the platform will be. Close blast, fast exit. Wide blast, safer ride.',
    intent: {
      primaryRoute: 'START -> B1 -> intercept moving platform -> right deck -> EXIT',
      launchJobs: [{ bomb: 'B1', job: 'Launch toward a future moving-platform position.' }],
      landingWindows: [{ target: 'moving platform', kind: 'medium', description: 'Prediction matters more than narrow geometry.' }],
      timingWindows: [{ target: 'moving platform', kind: 'intercept', description: 'Aim for the platform future, not its current position.' }],
      recovery: { kind: 'fatal', description: 'Missing the platform falls into the deep pit.' },
      masteryShortcut: 'A close, powerful launch can reach the exit deck before a long ride.',
      newConcept: 'Intercept a moving future state.',
      recombinedSkills: ['blast strength by proximity', 'air steering'],
      targetFirstClearSeconds: { min: 80, max: 200 },
    },
    validation: {},
    start: { x: 92, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 330, h: 50 },
      { x: 840, y: 450, w: 102, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 250, y: 532, delay: -2.8, label: 'B1' }],
    exit: { x: 876, y: 386, w: 54, h: 64 },
    pit: { x: 330, y: 450, w: 510, h: 150 },
    movingPlatform: {
      fromX: 440,
      toX: 700,
      y: 450,
      w: 140,
      h: 22,
      speed: 140,
      phase: 2.14,
    },
  },
  {
    id: 'level-7',
    name: 'LEVEL 7',
    subtitle: 'RETURN ARC',
    hint: 'Clear the hanging teeth after B1. Return left with B2, then launch from the left side of B3.',
    intent: {
      primaryRoute: 'START -> B1 -> lower deck -> B2 return left -> upper platform -> left side of B3 -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Clear hanging teeth and commit to the lower deck.' },
        { bomb: 'B2', job: 'Reverse traversal direction into the return arc.' },
        { bomb: 'B3', job: 'Launch from its left side into the upper-left exit.' },
      ],
      landingWindows: [
        { target: 'lower deck', kind: 'wide', description: 'The route decision, not landing precision, is primary.' },
        { target: 'upper platform', kind: 'medium', description: 'Catches imperfect return arcs.' },
      ],
      timingWindows: [{ target: 'B2', kind: 'expiring', description: 'Reach the lower deck before the useful B2 cycle passes.' }],
      recovery: { kind: 'recoverable', description: 'The upper platform rescues some imperfect return arcs.' },
      masteryShortcut: 'A clean B1 arc may reach the exit directly, but should be uncommon for first-time players.',
      newConcept: 'A blast reverses the route into a return arc.',
      recombinedSkills: ['blast timing', 'air steering', 'route hierarchy'],
      targetFirstClearSeconds: { min: 100, max: 240 },
    },
    validation: {},
    start: { x: 92, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 330, h: 50 },
      { x: 40, y: 140, w: 210, h: 22 },
      { x: 250, y: 300, w: 250, h: 22 },
      { x: 400, y: 470, w: 390, h: 22 },
      { x: 360, y: 70, w: 140, h: 20 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [
      { x: 250, y: 532, delay: -2.5, label: 'B1' },
      { x: 680, y: 452, delay: -0.2, label: 'B2' },
      { x: 400, y: 282, delay: 1.9, label: 'B3' },
    ],
    exit: { x: 120, y: 76, w: 54, h: 64 },
    spikes: [
      { x: 250, y: 322, w: 70, h: 58 },
      { x: 360, y: 90, w: 140, h: 70 },
    ],
    pit: { x: 330, y: 470, w: 630, h: 130 },
  },
  {
    id: 'level-8',
    name: 'LEVEL 8',
    subtitle: 'AIR SLALOM',
    hint: 'Hold right into the launch post. B1 lifts off, then flip direction on every blast: left, right, left, right.',
    intent: {
      primaryRoute: 'START -> launch post -> B1 -> B2 -> B3 -> B4 -> B5 -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Lift from the pinned launch position.' },
        { bomb: 'B2', job: 'Knock left and re-lift.' },
        { bomb: 'B3', job: 'Knock right and re-lift.' },
        { bomb: 'B4', job: 'Knock left and re-lift.' },
        { bomb: 'B5', job: 'Knock right into the combo-gated exit.' },
      ],
      landingWindows: [{ target: 'airborne exit', kind: 'none', description: 'There is no intermediate landing reset.' }],
      timingWindows: [{ target: 'B1–B5 relay', kind: 'expiring', description: 'The five fuse events form one committed airborne sequence.' }],
      recovery: { kind: 'fatal', description: 'A missed relay drops into the pit; the cycle restarts quickly.' },
      masteryShortcut: null,
      newConcept: 'A fully airborne five-blast slalom with load-bearing steering reversals.',
      recombinedSkills: ['air steering', 'air chaining', 'direction reversal'],
      targetFirstClearSeconds: { min: 120, max: 300 },
    },
    validation: {
      requiredBlastHits: ['B1', 'B2', 'B3', 'B4', 'B5'],
      minimumAirCombo: 5,
      simplePoliciesMustFail: ['hold-left', 'neutral', 'hold-right'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 30, samples: 100, minimumClearRate: 0.6 },
        { jitterMilliseconds: 80, samples: 100, minimumClearRate: 0.25 },
      ],
    },
    start: { x: 92, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 484, h: 50 },
      { x: 470, y: 508, w: 14, h: 42 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [
      { x: 410, y: 532, delay: -2.4, label: 'B1' },
      { x: 590, y: 452, delay: -1.9, label: 'B2', floating: true },
      { x: 445, y: 346, delay: -1.5, label: 'B3', floating: true },
      { x: 656, y: 213, delay: -1.1, label: 'B4', floating: true },
      { x: 491, y: 135, delay: -0.7, label: 'B5', floating: true },
    ],
    exit: { x: 550, y: 97, w: 86, h: 70 },
    pit: { x: 484, y: 500, w: 476, h: 100 },
    requiredCombo: 5,
  },
  {
    id: 'level-9',
    name: 'LEVEL 9',
    subtitle: 'COLD START',
    hint: 'Pass through coolant. Carry the blue state across the hot plate, then use the charge.',
    intent: {
      primaryRoute: 'START -> coolant source -> cool HOT PLATE -> cross safely -> pass B1 -> blast into upper shaft -> steer left -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Launch from the right wall up the open shaft, then allow a leftward landing on the exit deck.' },
      ],
      landingWindows: [{ target: 'upper exit deck', kind: 'wide', description: 'Cold is the new lesson; the returning landing is intentionally broad.' }],
      timingWindows: [
        { target: 'cooled hot plate', kind: 'open', description: 'The coolant source is unavoidable and refreshable before crossing.' },
        { target: 'B1 launch', kind: 'commit', description: 'Reach the right launch wall for the prepared blast, then steer left above the deck.' },
      ],
      recovery: { kind: 'safe', description: 'The cooled plate and right floor are stable; incorrect neutral contact resets immediately and readably.' },
      masteryShortcut: null,
      newConcept: 'A temporary cold state makes one visibly overheated factory surface safe.',
      recombinedSkills: ['blast proximity', 'midair steering'],
      targetFirstClearSeconds: { min: 55, max: 140 },
    },
    validation: {
      requiredBlastHits: ['B1'],
      requiredInteractions: ['hot-plate-cooling'],
      requiredStates: ['cold'],
      simplePoliciesMustFail: ['hold-left', 'neutral', 'hold-right'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 100, samples: 100, minimumClearRate: 0.8 },
      ],
    },
    start: { x: 82, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 360, h: 50 },
      { x: 360, y: 550, w: 270, h: 50 },
      { x: 630, y: 550, w: 312, h: 50 },
      { x: 620, y: 350, w: 250, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 900, y: 532, delay: -1.5, label: 'B1' }],
    exit: { x: 700, y: 286, w: 64, h: 64 },
    traversalStateSources: [
      {
        id: 'coolant-gate',
        rect: { x: 150, y: 500, w: 92, h: 50 },
        grants: 'cold',
        durationSeconds: 7,
      },
    ],
    traversalInteractions: [
      {
        id: 'hot-plate-cooling',
        rect: { x: 344, y: 500, w: 302, h: 54 },
        kind: 'cool-surface',
        accepts: ['cold'],
        activeSeconds: 5,
      },
    ],
    hotSurfaces: [
      {
        id: 'hot-plate',
        rect: { x: 360, y: 542, w: 270, h: 12 },
        cooledByInteractionId: 'hot-plate-cooling',
      },
    ],
  },
  {
    id: 'level-10',
    name: 'LEVEL 10',
    subtitle: 'CONDENSATE GAP',
    hint: 'Carry coolant to the dripping edge. Cross while the frozen path holds, then use the charge.',
    intent: {
      primaryRoute: 'START -> coolant source -> freeze condensate -> cross temporary ice -> pass B1 -> blast into upper shaft -> steer left -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Launch from the right wall up the open shaft, then allow a leftward landing on the exit deck.' },
      ],
      landingWindows: [
        { target: 'frozen condensate bridge', kind: 'wide', description: 'The new temporary surface spans the whole water gap.' },
        { target: 'upper exit deck', kind: 'wide', description: 'The familiar blast landing remains forgiving while freezing is learned.' },
      ],
      timingWindows: [
        { target: 'frozen bridge', kind: 'expiring', description: 'The bridge lasts long enough for a readable crossing and then thaws deterministically.' },
        { target: 'B1 launch', kind: 'commit', description: 'Reach the far launch wall for the prepared blast, then steer left above the deck.' },
      ],
      recovery: { kind: 'fatal', description: 'A short crossing enters the water; the far bank is stable once reached.' },
      masteryShortcut: null,
      newConcept: 'Cold freezes one water span into a temporary collision surface.',
      recombinedSkills: ['cold acquisition', 'blast proximity', 'midair steering'],
      targetFirstClearSeconds: { min: 65, max: 150 },
    },
    validation: {
      requiredBlastHits: ['B1'],
      requiredInteractions: ['condensate-freeze'],
      requiredStates: ['cold'],
      simplePoliciesMustFail: ['hold-left', 'neutral', 'hold-right'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 100, samples: 100, minimumClearRate: 0.8 },
      ],
    },
    start: { x: 82, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 320, h: 50 },
      { x: 650, y: 550, w: 292, h: 50 },
      { x: 620, y: 350, w: 250, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 900, y: 532, delay: -1.5, label: 'B1' }],
    exit: { x: 700, y: 286, w: 64, h: 64 },
    traversalStateSources: [
      {
        id: 'coolant-gate',
        rect: { x: 130, y: 500, w: 92, h: 50 },
        grants: 'cold',
        durationSeconds: 7,
      },
    ],
    traversalInteractions: [
      {
        id: 'condensate-freeze',
        rect: { x: 292, y: 494, w: 56, h: 60 },
        kind: 'freeze-water',
        accepts: ['cold'],
        activeSeconds: 4.8,
        resultRect: { x: 320, y: 550, w: 330, h: 18 },
      },
    ],
    waterHazards: [
      {
        id: 'condensate-pool',
        rect: { x: 320, y: 550, w: 330, h: 50 },
        frozenByInteractionId: 'condensate-freeze',
      },
    ],
  },
  {
    id: 'level-11',
    name: 'LEVEL 11',
    subtitle: 'COLD LOCK',
    hint: 'Chill the carriage control. Launch while the transfer deck is held at the blue dock.',
    intent: {
      primaryRoute: 'START -> coolant source -> stabilize transfer carriage -> B1 -> locked carriage -> right inspection deck -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Launch from the left floor onto the carriage held at its marked dock.' },
      ],
      landingWindows: [
        { target: 'locked transfer carriage', kind: 'wide', description: 'The fixed carriage and adjoining inspection deck form a broad landing region.' },
      ],
      timingWindows: [
        { target: 'carriage lock', kind: 'expiring', description: 'The cold lock lasts through the prepared launch and landing, then releases the normal cycle.' },
        { target: 'B1 launch', kind: 'commit', description: 'The launch post fixes the takeoff position for the prepared blast.' },
      ],
      recovery: { kind: 'fatal', description: 'Missing the carriage falls into the machinery pit; the start floor is safe before launch.' },
      masteryShortcut: null,
      newConcept: 'Cold temporarily fixes a moving transfer carriage at its marked dock.',
      recombinedSkills: ['cold acquisition', 'blast proximity', 'midair steering'],
      targetFirstClearSeconds: { min: 70, max: 165 },
    },
    validation: {
      requiredBlastHits: ['B1'],
      requiredInteractions: ['carriage-lock'],
      requiredStates: ['cold'],
      simplePoliciesMustFail: ['hold-left', 'neutral'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 100, samples: 100, minimumClearRate: 0.75 },
      ],
    },
    start: { x: 82, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 330, h: 50 },
      { x: 316, y: 508, w: 14, h: 42 },
      { x: 700, y: 450, w: 242, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 250, y: 532, delay: -2.5, label: 'B1' }],
    exit: { x: 716, y: 386, w: 64, h: 64 },
    pit: { x: 330, y: 450, w: 370, h: 150 },
    movingPlatform: {
      fromX: 350,
      toX: 700,
      y: 450,
      w: 370,
      h: 22,
      speed: 160,
      phase: 0.4,
      stabilizedByInteractionId: 'carriage-lock',
      stabilizedX: 330,
    },
    traversalStateSources: [
      {
        id: 'coolant-gate',
        rect: { x: 100, y: 500, w: 82, h: 50 },
        grants: 'cold',
        durationSeconds: 7,
      },
    ],
    traversalInteractions: [
      {
        id: 'carriage-lock',
        rect: { x: 190, y: 492, w: 82, h: 62 },
        kind: 'stabilize-machine',
        accepts: ['cold'],
        activeSeconds: 5.5,
      },
    ],
  },
  {
    id: 'level-12',
    name: 'LEVEL 12',
    subtitle: 'THAW CLOCK',
    hint: 'Freeze the trench and commit. Reach the far charge before the blue route thaws.',
    intent: {
      primaryRoute: 'START -> coolant source -> freeze long condensate trench -> cross to launch stop -> B1 before thaw -> steer left -> upper exit deck -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Launch from the far end of the expiring ice on its first fuse, then reverse left into the exit deck.' },
      ],
      landingWindows: [
        { target: 'frozen condensate trench', kind: 'wide', description: 'The full route freezes; speed rather than foot precision matters.' },
        { target: 'upper exit deck', kind: 'wide', description: 'A correct first-cycle launch has a broad returning landing.' },
      ],
      timingWindows: [
        { target: 'frozen trench', kind: 'expiring', description: 'The ice thaws just after the useful first B1 fuse and cannot survive to the repeat cycle.' },
        { target: 'B1 launch', kind: 'commit', description: 'Cross immediately and use the prepared blast before the route disappears.' },
      ],
      recovery: { kind: 'fatal', description: 'The start floor is safe before commitment; a late crossing or missed first blast falls into water.' },
      masteryShortcut: null,
      newConcept: 'No new mechanic; existing temporary ice becomes a load-bearing blast timer.',
      recombinedSkills: ['cold acquisition', 'temporary ice', 'prepared blast timing', 'midair reversal'],
      targetFirstClearSeconds: { min: 80, max: 185 },
    },
    validation: {
      requiredBlastHits: ['B1'],
      requiredInteractions: ['thaw-clock-freeze'],
      requiredStates: ['cold'],
      simplePoliciesMustFail: ['hold-left', 'neutral', 'hold-right'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 80, samples: 100, minimumClearRate: 0.7 },
      ],
    },
    start: { x: 72, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 300, h: 50 },
      { x: 900, y: 508, w: 14, h: 42 },
      { x: 610, y: 350, w: 260, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 850, y: 532, delay: -0.8, label: 'B1' }],
    exit: { x: 690, y: 286, w: 64, h: 64 },
    traversalStateSources: [
      {
        id: 'coolant-gate',
        rect: { x: 100, y: 500, w: 82, h: 50 },
        grants: 'cold',
        durationSeconds: 7,
      },
    ],
    traversalInteractions: [
      {
        id: 'thaw-clock-freeze',
        rect: { x: 272, y: 492, w: 58, h: 62 },
        kind: 'freeze-water',
        accepts: ['cold'],
        activeSeconds: 3.35,
        resultRect: { x: 300, y: 550, w: 600, h: 18 },
      },
    ],
    waterHazards: [
      {
        id: 'thaw-clock-pool',
        rect: { x: 300, y: 550, w: 600, h: 50 },
        frozenByInteractionId: 'thaw-clock-freeze',
      },
    ],
  },
  {
    id: 'level-13',
    name: 'LEVEL 13',
    subtitle: 'COLD CATCH',
    hint: 'Freeze the basin. A clean B1 arc exits; a short arc can recover through B2.',
    intent: {
      primaryRoute: 'START -> coolant source -> freeze catch basin -> B1 -> upper exit deck -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Launch from the frozen approach directly to the upper exit deck.' },
        { bomb: 'B2', job: 'Relaunch an over-braked B1 attempt from the lower frozen recovery route.' },
      ],
      landingWindows: [
        { target: 'upper exit deck', kind: 'medium', description: 'The clean B1 arc needs readable braking but not a tight landing.' },
        { target: 'frozen catch basin', kind: 'wide', description: 'A plausible short B1 arc survives on the lower cold-created surface.' },
      ],
      timingWindows: [
        { target: 'B1 launch', kind: 'commit', description: 'The first prepared blast starts either the clean or recovery route.' },
        { target: 'B2 recovery', kind: 'expiring', description: 'The ice remains long enough for one recovery launch before thawing.' },
      ],
      recovery: { kind: 'recoverable', description: 'An over-braked B1 arc lands on frozen water, then routes right through B2.' },
      masteryShortcut: null,
      newConcept: 'Existing frozen geometry supports both a primary approach and a distinct recovery state.',
      recombinedSkills: ['temporary ice', 'blast landing control', 'secondary blast recovery', 'midair steering'],
      targetFirstClearSeconds: { min: 90, max: 210 },
    },
    validation: {
      requiredBlastHits: ['B1'],
      requiredInteractions: ['catch-basin-freeze'],
      requiredStates: ['cold'],
      simplePoliciesMustFail: ['hold-left', 'neutral'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 30, samples: 100, minimumClearRate: 0.8 },
      ],
    },
    start: { x: 72, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 300, h: 50 },
      { x: 600, y: 508, w: 14, h: 42 },
      { x: 700, y: 350, w: 200, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [
      { x: 550, y: 532, delay: -1.8, label: 'B1' },
      { x: 585, y: 532, delay: 0.6, label: 'B2' },
    ],
    exit: { x: 790, y: 286, w: 64, h: 64 },
    traversalStateSources: [
      {
        id: 'coolant-gate',
        rect: { x: 100, y: 500, w: 82, h: 50 },
        grants: 'cold',
        durationSeconds: 8,
      },
    ],
    traversalInteractions: [
      {
        id: 'catch-basin-freeze',
        rect: { x: 272, y: 492, w: 32, h: 62 },
        kind: 'freeze-water',
        accepts: ['cold'],
        activeSeconds: 7,
        resultRect: { x: 300, y: 550, w: 600, h: 18 },
      },
    ],
    waterHazards: [
      {
        id: 'catch-basin-pool',
        rect: { x: 300, y: 550, w: 600, h: 50 },
        frozenByInteractionId: 'catch-basin-freeze',
      },
    ],
  },
  {
    id: 'level-14',
    name: 'LEVEL 14',
    subtitle: 'BLUE CIRCUIT',
    hint: 'Freeze the intake, lock the carriage, then route B1 to B2. A perfect B1 position can go higher.',
    intent: {
      primaryRoute: 'START -> coolant -> freeze intake gap -> lock transfer carriage -> B1 from primary stop -> locked carriage -> B2 -> upper exit deck -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Use an offset launch from the primary stop to reach the stabilized carriage.' },
        { bomb: 'B2', job: 'Launch vertically from the right stop, then steer left into the upper exit deck.' },
      ],
      landingWindows: [
        { target: 'locked transfer carriage', kind: 'wide', description: 'A correct offset B1 setup lands on a broad stabilized surface.' },
        { target: 'upper exit deck', kind: 'medium', description: 'B2 needs a deliberate leftward return after clearing the deck edge.' },
      ],
      timingWindows: [
        { target: 'ice and carriage lock', kind: 'expiring', description: 'Both cold-created route pieces cover one prepared B1-to-B2 sequence.' },
        { target: 'B2 return', kind: 'commit', description: 'Clear the right edge vertically, then steer left before descending.' },
      ],
      recovery: { kind: 'recoverable', description: 'The locked carriage catches a range of imperfect primary B1 arcs; missing it falls into the basin.' },
      masteryShortcut: 'Stop directly over B1 instead of at the primary stop; the stronger vertical launch reaches the upper deck without B2.',
      newConcept: 'No new mechanic; ice, machinery lock, blast distance, and route hierarchy form the cold finale.',
      recombinedSkills: ['temporary ice', 'cold machinery lock', 'proximity strength', 'air steering', 'chained route planning'],
      targetFirstClearSeconds: { min: 120, max: 260 },
    },
    validation: {
      requiredBlastHits: ['B1', 'B2'],
      requiredInteractions: ['circuit-intake-freeze', 'circuit-carriage-lock'],
      requiredStates: ['cold'],
      simplePoliciesMustFail: ['hold-left', 'neutral', 'hold-right'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 80, samples: 100, minimumClearRate: 0.6 },
      ],
    },
    start: { x: 72, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 300, h: 50 },
      { x: 480, y: 550, w: 170, h: 50 },
      { x: 636, y: 508, w: 14, h: 42 },
      { x: 900, y: 428, w: 14, h: 42 },
      { x: 650, y: 220, w: 200, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [
      { x: 570, y: 532, delay: -1.6, label: 'B1' },
      { x: 887, y: 452, delay: 0.6, label: 'B2' },
    ],
    exit: { x: 730, y: 156, w: 64, h: 64 },
    pit: { x: 650, y: 470, w: 292, h: 130 },
    movingPlatform: {
      fromX: 380,
      toX: 650,
      y: 470,
      w: 250,
      h: 22,
      speed: 150,
      phase: 0.45,
      stabilizedByInteractionId: 'circuit-carriage-lock',
      stabilizedX: 650,
    },
    traversalStateSources: [
      {
        id: 'coolant-gate',
        rect: { x: 100, y: 500, w: 82, h: 50 },
        grants: 'cold',
        durationSeconds: 10,
      },
    ],
    traversalInteractions: [
      {
        id: 'circuit-intake-freeze',
        rect: { x: 272, y: 492, w: 32, h: 62 },
        kind: 'freeze-water',
        accepts: ['cold'],
        activeSeconds: 9,
        resultRect: { x: 300, y: 550, w: 180, h: 18 },
      },
      {
        id: 'circuit-carriage-lock',
        rect: { x: 500, y: 492, w: 70, h: 62 },
        kind: 'stabilize-machine',
        accepts: ['cold'],
        activeSeconds: 6.5,
      },
    ],
    waterHazards: [
      {
        id: 'circuit-intake-pool',
        rect: { x: 300, y: 550, w: 180, h: 50 },
        frozenByInteractionId: 'circuit-intake-freeze',
      },
    ],
  },
  {
    id: 'level-15',
    name: 'LEVEL 15',
    subtitle: 'THERMAL SEAL',
    hint: 'Pass through the furnace duct. Carry the red state into the sealed partition, then use the charge.',
    intent: {
      primaryRoute: 'START -> furnace duct -> acquire heat -> melt sealed partition -> cross opened threshold -> B1 at right wall -> steer left -> upper exit deck -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Use the familiar right-wall launch, then steer left into the broad upper exit deck.' },
      ],
      landingWindows: [
        { target: 'upper exit deck', kind: 'wide', description: 'Heat is the new lesson; the returning blast landing stays intentionally broad.' },
      ],
      timingWindows: [
        { target: 'melted partition', kind: 'open', description: 'The seal remains open long enough for a comfortable, readable crossing.' },
        { target: 'B1 launch', kind: 'commit', description: 'Reach the right wall for the prepared blast, then steer left above the deck.' },
      ],
      recovery: { kind: 'safe', description: 'Rejected contact visibly stops at the seal; after crossing, the right floor is stable before B1.' },
      masteryShortcut: null,
      newConcept: 'A temporary heat state melts one unmistakable solid factory partition out of authoritative collision.',
      recombinedSkills: ['temporary-state acquisition', 'blast proximity', 'midair steering'],
      targetFirstClearSeconds: { min: 55, max: 140 },
    },
    validation: {
      requiredBlastHits: ['B1'],
      requiredInteractions: ['thermal-seal-melt'],
      requiredStates: ['heat'],
      simplePoliciesMustFail: ['hold-left', 'neutral', 'hold-right'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 100, samples: 100, minimumClearRate: 0.8 },
      ],
    },
    start: { x: 82, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 942, h: 50 },
      { x: 620, y: 350, w: 250, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 900, y: 532, delay: -1.5, label: 'B1' }],
    exit: { x: 700, y: 286, w: 64, h: 64 },
    traversalStateSources: [
      {
        id: 'furnace-duct',
        rect: { x: 150, y: 500, w: 92, h: 50 },
        grants: 'heat',
        durationSeconds: 7,
      },
    ],
    traversalInteractions: [
      {
        id: 'thermal-seal-melt',
        rect: { x: 332, y: 300, w: 58, h: 254 },
        kind: 'melt-barrier',
        accepts: ['heat'],
        activeSeconds: 7,
      },
    ],
    meltableBarriers: [
      {
        id: 'thermal-seal',
        rect: { x: 360, y: 300, w: 30, h: 250 },
        meltedByInteractionId: 'thermal-seal-melt',
      },
    ],
  },
  {
    id: 'level-16',
    name: 'LEVEL 16',
    subtitle: 'REIGNITION',
    hint: 'Carry furnace heat into the ignition terminal. When the dormant charge wakes, take position.',
    intent: {
      primaryRoute: 'START -> furnace duct -> acquire heat -> ignition terminal -> power dormant B1 -> right launch wall -> wait for powered fuse -> B1 -> steer left -> upper exit deck -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'After reactivation, perform a familiar right-wall launch and return left into the broad upper deck.' },
      ],
      landingWindows: [
        { target: 'upper exit deck', kind: 'wide', description: 'Charge reactivation is the new lesson; landing remains deliberately forgiving.' },
      ],
      timingWindows: [
        { target: 'powered B1 fuse', kind: 'open', description: 'The ignition interval covers the full first fuse and gives ample setup time at the wall.' },
        { target: 'B1 launch', kind: 'commit', description: 'Wait at the right wall, then reverse left as the newly powered charge fires.' },
      ],
      recovery: { kind: 'safe', description: 'Without power the charge remains visibly dormant beside stable floor; no blind hazard is introduced.' },
      masteryShortcut: null,
      newConcept: 'Heat powers a linked dormant blast charge so its authoritative fuse advances only while the ignition circuit is active.',
      recombinedSkills: ['heat acquisition', 'prepared blast timing', 'blast proximity', 'midair steering'],
      targetFirstClearSeconds: { min: 70, max: 160 },
    },
    validation: {
      requiredBlastHits: ['B1'],
      requiredInteractions: ['charge-ignition'],
      requiredStates: ['heat'],
      simplePoliciesMustFail: ['hold-left', 'neutral', 'hold-right'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 100, samples: 100, minimumClearRate: 0.8 },
      ],
    },
    start: { x: 82, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 942, h: 50 },
      { x: 620, y: 350, w: 250, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [
      {
        x: 900,
        y: 532,
        delay: -1.4,
        label: 'B1',
        reactivatedByInteractionId: 'charge-ignition',
      },
    ],
    exit: { x: 700, y: 286, w: 64, h: 64 },
    traversalStateSources: [
      {
        id: 'furnace-duct',
        rect: { x: 150, y: 500, w: 92, h: 50 },
        grants: 'heat',
        durationSeconds: 7,
      },
    ],
    traversalInteractions: [
      {
        id: 'charge-ignition',
        rect: { x: 340, y: 500, w: 90, h: 54 },
        kind: 'reactivate-charge',
        accepts: ['heat'],
        activeSeconds: 10,
      },
    ],
  },
  {
    id: 'level-17',
    name: 'LEVEL 17',
    subtitle: 'HEAT WINDOW',
    hint: 'The upper seal is far from the furnace. Take the red state when the charge is nearly ready.',
    intent: {
      primaryRoute: 'Wait before furnace lane -> acquire heat late -> right-wall B1 before expiry -> launch left -> melt upper thermal seal -> upper exit -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Launch from the right wall toward the upper deck and its heat-locked left section.' },
      ],
      landingWindows: [
        { target: 'upper exit deck', kind: 'wide', description: 'The seal spans the intended leftward path; the deck itself remains broad.' },
      ],
      timingWindows: [
        { target: 'heat pickup', kind: 'commit', description: 'Immediate pickup expires before the upper seal; a seconds-wide delayed pickup survives the B1 route.' },
        { target: 'B1 launch', kind: 'expiring', description: 'Reach the prepared first-cycle blast with enough heat lifetime remaining for the upper interaction.' },
      ],
      recovery: { kind: 'recoverable', description: 'A rejected upper seal drops the player to safe lower floor for another furnace pickup and repeating B1 cycle.' },
      masteryShortcut: null,
      newConcept: 'No new mechanic; remaining heat lifetime becomes an explicit route-planning resource.',
      recombinedSkills: ['heat acquisition', 'timed barrier melting', 'prepared blast cycle', 'airborne reversal', 'safe reset routing'],
      targetFirstClearSeconds: { min: 120, max: 220 },
    },
    validation: {
      requiredBlastHits: ['B1'],
      requiredInteractions: ['upper-seal-melt'],
      requiredStates: ['heat'],
      simplePoliciesMustFail: ['hold-left', 'neutral', 'hold-right'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 100, samples: 100, minimumClearRate: 0.75 },
      ],
    },
    start: { x: 82, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 942, h: 50 },
      { x: 520, y: 350, w: 350, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 900, y: 532, delay: 0, label: 'B1' }],
    exit: { x: 550, y: 286, w: 64, h: 64 },
    traversalStateSources: [
      {
        id: 'furnace-lane',
        rect: { x: 650, y: 500, w: 92, h: 50 },
        grants: 'heat',
        durationSeconds: 3.2,
      },
    ],
    traversalInteractions: [
      {
        id: 'upper-seal-melt',
        rect: { x: 622, y: 200, w: 88, h: 154 },
        kind: 'melt-barrier',
        accepts: ['heat'],
        activeSeconds: 6,
      },
    ],
    meltableBarriers: [
      {
        id: 'upper-thermal-seal',
        rect: { x: 650, y: 210, w: 30, h: 140 },
        meltedByInteractionId: 'upper-seal-melt',
      },
    ],
  },
  {
    id: 'level-18',
    name: 'LEVEL 18',
    subtitle: 'PHASE SHIFT',
    hint: 'Blue makes the vapor span solid. Red opens the same span when you need the lower line.',
    intent: {
      primaryRoute: 'Upper-left start -> coolant -> freeze shared vapor span -> cross upper shaft -> furnace -> replace cold with heat -> thaw same span -> return left into right side of open shaft -> lower-right line -> B1 at divider -> upper-right exit -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Launch from the lower divider through the newly reopened span, then steer right to the upper exit.' },
      ],
      landingWindows: [
        { target: 'condensed vapor bridge', kind: 'wide', description: 'Cold creates a full-width crossing between the upper decks.' },
        { target: 'upper-right exit deck', kind: 'wide', description: 'B1 returns to the broad deck already read during the thermal route.' },
      ],
      timingWindows: [
        { target: 'freeze and thaw controls', kind: 'open', description: 'Both state interactions last comfortably; order and spatial planning are the challenge.' },
        { target: 'B1 launch', kind: 'commit', description: 'After the right-side drop, settle at the lower divider before the prepared blast.' },
      ],
      recovery: { kind: 'recoverable', description: 'Falling before condensation returns to blocked lower-left floor; keeping the bridge frozen leaves a safe upper route that exposes the missing heat step.' },
      masteryShortcut: null,
      newConcept: 'Heat explicitly deactivates the cold-created state of the same data-linked factory system.',
      recombinedSkills: ['state replacement', 'temporary frozen collision', 'heat interaction', 'route-state planning', 'blast return'],
      targetFirstClearSeconds: { min: 150, max: 260 },
    },
    validation: {
      requiredBlastHits: ['B1'],
      requiredInteractions: ['phase-span-freeze', 'phase-span-thaw'],
      requiredStates: ['cold', 'heat'],
      simplePoliciesMustFail: ['hold-left', 'neutral', 'hold-right'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 80, samples: 100, minimumClearRate: 0.7 },
      ],
    },
    start: { x: 82, y: 314 },
    platforms: [
      { x: 0, y: 350, w: 300, h: 22 },
      { x: 600, y: 350, w: 270, h: 22 },
      { x: 620, y: 280, w: 250, h: 22 },
      { x: 0, y: 550, w: 942, h: 50 },
      { x: 480, y: 372, w: 40, h: 178 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 533, y: 532, delay: 2.4, label: 'B1' }],
    exit: { x: 700, y: 216, w: 64, h: 64 },
    traversalStateSources: [
      {
        id: 'phase-coolant',
        rect: { x: 100, y: 300, w: 92, h: 50 },
        grants: 'cold',
        durationSeconds: 9,
      },
      {
        id: 'phase-furnace',
        rect: { x: 650, y: 300, w: 92, h: 50 },
        grants: 'heat',
        durationSeconds: 8,
      },
    ],
    traversalInteractions: [
      {
        id: 'phase-span-freeze',
        rect: { x: 272, y: 292, w: 32, h: 62 },
        kind: 'freeze-water',
        accepts: ['cold'],
        activeSeconds: 9,
        resultRect: { x: 300, y: 350, w: 300, h: 18 },
      },
      {
        id: 'phase-span-thaw',
        rect: { x: 760, y: 296, w: 90, h: 58 },
        kind: 'thaw-ice',
        accepts: ['heat'],
        deactivatesInteractionId: 'phase-span-freeze',
      },
    ],
  },
  {
    id: 'level-19',
    name: 'LEVEL 19',
    subtitle: 'THERMAL CATCH',
    hint: 'Heat opens the fast launch. If B1 falls short, the emergency quench line can turn the basin into a second route.',
    intent: {
      primaryRoute: 'START -> furnace heat -> melt launch seal -> B1 from prepared edge -> upper exit deck -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Drive the fast heat route directly toward the upper exit deck.' },
        { bomb: 'B2', job: 'Relaunch only a missed B1 attempt from the lower cold-created recovery span.' },
      ],
      landingWindows: [
        { target: 'upper exit deck', kind: 'medium', description: 'The fast B1 route rewards a clean launch without making the target narrow.' },
        { target: 'emergency coolant catch', kind: 'wide', description: 'A plausible short B1 arc enters a broad quench zone that freezes the basin before contact.' },
      ],
      timingWindows: [
        { target: 'heat-opened B1', kind: 'commit', description: 'The launch seal stays open through the prepared first blast.' },
        { target: 'cold B2 recovery', kind: 'expiring', description: 'Emergency ice covers one readable B2 cycle instead of becoming permanent floor.' },
      ],
      recovery: { kind: 'recoverable', description: 'Falling short replaces heat with cold, freezes the lower basin, and exposes B2 as a slower route to the same exit.' },
      masteryShortcut: null,
      newConcept: 'No new mechanic; heat owns the primary route while cold appears only on the recovery branch.',
      recombinedSkills: ['heat barrier melting', 'blast proximity', 'midair braking', 'cold acquisition', 'temporary ice', 'secondary blast recovery'],
      targetFirstClearSeconds: { min: 180, max: 300 },
    },
    validation: {
      requiredBlastHits: ['B1'],
      requiredInteractions: ['launch-seal-melt'],
      requiredStates: ['heat'],
      simplePoliciesMustFail: ['hold-left', 'neutral'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 30, samples: 100, minimumClearRate: 0.8 },
      ],
    },
    start: { x: 72, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 300, h: 50 },
      { x: 286, y: 508, w: 14, h: 42 },
      { x: 900, y: 508, w: 14, h: 42 },
      { x: 520, y: 350, w: 300, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [
      { x: 273, y: 532, delay: -1.8, label: 'B1' },
      { x: 887, y: 532, delay: 2, label: 'B2' },
    ],
    exit: { x: 650, y: 286, w: 64, h: 64 },
    traversalStateSources: [
      {
        id: 'launch-furnace',
        rect: { x: 80, y: 500, w: 82, h: 50 },
        grants: 'heat',
        durationSeconds: 8,
      },
      {
        id: 'emergency-quench',
        rect: { x: 300, y: 480, w: 220, h: 74 },
        grants: 'cold',
        durationSeconds: 8,
      },
    ],
    traversalInteractions: [
      {
        id: 'launch-seal-melt',
        rect: { x: 192, y: 396, w: 58, h: 158 },
        kind: 'melt-barrier',
        accepts: ['heat'],
        activeSeconds: 8,
      },
      {
        id: 'emergency-basin-freeze',
        rect: { x: 300, y: 480, w: 230, h: 74 },
        kind: 'freeze-water',
        accepts: ['cold'],
        activeSeconds: 5,
        resultRect: { x: 300, y: 550, w: 600, h: 18 },
      },
    ],
    meltableBarriers: [
      {
        id: 'launch-thermal-seal',
        rect: { x: 220, y: 396, w: 30, h: 154 },
        meltedByInteractionId: 'launch-seal-melt',
      },
    ],
    waterHazards: [
      {
        id: 'emergency-basin',
        rect: { x: 300, y: 550, w: 600, h: 50 },
        frozenByInteractionId: 'emergency-basin-freeze',
      },
    ],
  },
  {
    id: 'level-20',
    name: 'LEVEL 20',
    subtitle: 'INDUCTION RAIL',
    hint: 'Take the green charge. B1 can place you on the overhead rail; keep moving before the lock discharges.',
    intent: {
      primaryRoute: 'START -> induction coil -> magnetic state -> prepared B1 -> overhead rail capture -> automatic attachment -> move right along bounded rail -> automatic end release -> right exit platform -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Lift the magnetized player into the rail capture band; the rail carries the long horizontal crossing.' },
      ],
      landingWindows: [
        { target: 'magnetic rail capture band', kind: 'wide', description: 'The capture zone surrounds the intended B1 apex and does not require a pixel-perfect touch.' },
        { target: 'right exit platform', kind: 'wide', description: 'The platform sits directly beneath automatic rail-end release.' },
      ],
      timingWindows: [
        { target: 'magnetic attachment', kind: 'expiring', description: 'Attachment comfortably covers one rightward crossing but expires if the player waits over the void.' },
        { target: 'rail end', kind: 'open', description: 'Crossing the data-defined end releases automatically without another button.' },
      ],
      recovery: { kind: 'fatal', description: 'Missing capture or exhausting attachment over the central void drops out; the start platform is safe before B1.' },
      masteryShortcut: null,
      newConcept: 'A rising magnetic player automatically attaches to a bounded rail, moves along it with left/right, and releases at its end or on expiry.',
      recombinedSkills: ['temporary-state acquisition', 'prepared blast launch', 'horizontal steering', 'release-point landing'],
      targetFirstClearSeconds: { min: 80, max: 180 },
    },
    validation: {
      requiredBlastHits: ['B1'],
      requiredInteractions: ['induction-rail'],
      requiredStates: ['magnetic'],
      simplePoliciesMustFail: ['hold-left', 'neutral'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 80, samples: 100, minimumClearRate: 0.8 },
      ],
    },
    start: { x: 72, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 320, h: 50 },
      { x: 286, y: 508, w: 14, h: 42 },
      { x: 760, y: 350, w: 182, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 273, y: 532, delay: -1.8, label: 'B1' }],
    exit: { x: 878, y: 286, w: 64, h: 64 },
    pit: { x: 320, y: 350, w: 440, h: 250 },
    traversalStateSources: [
      {
        id: 'induction-coil',
        rect: { x: 80, y: 500, w: 82, h: 50 },
        grants: 'magnetic',
        durationSeconds: 8,
      },
    ],
    traversalInteractions: [
      {
        id: 'induction-rail',
        rect: { x: 230, y: 130, w: 590, h: 100 },
        kind: 'magnetic-attach',
        accepts: ['magnetic'],
        activeSeconds: 4,
        resultRect: { x: 250, y: 150, w: 550, h: 16 },
      },
    ],
  },
  {
    id: 'level-21',
    name: 'LEVEL 21',
    subtitle: 'SHIFT CARRIER',
    hint: 'Read the carrier cycle. B1 catches it at the left dock; shift right once aboard, then ride to receiving.',
    intent: {
      primaryRoute: 'START -> induction coil -> magnetic state -> read the overhead carrier cycle -> prepared B1 -> moving capture -> shift right aboard -> ride to the receiving end -> automatic carrier-end release -> right deck -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'Lift the magnetized player into the carrier as it reaches the left dock; the carrier owns the long crossing.' },
      ],
      landingWindows: [
        { target: 'moving carrier capture band', kind: 'wide', description: 'The carrier has explicit horizontal and lower capture padding around the intended B1 apex.' },
        { target: 'right receiving deck', kind: 'wide', description: 'One short rightward shift aboard places the player over the broad deck before automatic end release.' },
      ],
      timingWindows: [
        { target: 'left-dock interception', kind: 'intercept', description: 'The carrier arrives at the launch lane on the prepared B1 cycle and repeats visibly if the player waits.' },
        { target: 'carrier attachment', kind: 'expiring', description: 'Attachment covers one complete left-to-right trip but discharges if the player refuses the route.' },
      ],
      recovery: { kind: 'recoverable', description: 'The start floor is safe while reading the cycle; a missed airborne interception falls into the exposed water trench.' },
      masteryShortcut: null,
      newConcept: 'A bounded magnetic attachment can follow a moving rail, inheriting its displacement while preserving left/right positioning and automatic endpoint release.',
      recombinedSkills: ['temporary magnetic state', 'prepared blast timing', 'moving-target interception', 'bounded rail traversal', 'release-point landing'],
      targetFirstClearSeconds: { min: 100, max: 240 },
    },
    validation: {
      requiredBlastHits: ['B1'],
      requiredInteractions: ['shift-carrier'],
      requiredStates: ['magnetic'],
      simplePoliciesMustFail: ['hold-left', 'neutral', 'hold-right'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 120, samples: 100, minimumClearRate: 0.8 },
      ],
    },
    start: { x: 72, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 320, h: 50 },
      { x: 286, y: 508, w: 14, h: 42 },
      { x: 720, y: 380, w: 222, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [{ x: 273, y: 532, delay: -1.8, label: 'B1' }],
    exit: { x: 760, y: 316, w: 140, h: 64 },
    pit: { x: 320, y: 380, w: 400, h: 220 },
    traversalStateSources: [
      {
        id: 'carrier-coil',
        rect: { x: 80, y: 500, w: 82, h: 50 },
        grants: 'magnetic',
        durationSeconds: 10,
      },
    ],
    traversalInteractions: [
      {
        id: 'shift-carrier',
        rect: { x: 210, y: 130, w: 610, h: 120 },
        kind: 'magnetic-attach',
        accepts: ['magnetic'],
        activeSeconds: 5,
        movingResult: {
          fromX: 230,
          toX: 600,
          y: 155,
          w: 200,
          h: 16,
          speed: 85,
          phase: 5.2558823529,
        },
        movingCapturePadding: { horizontal: 20, above: 10, below: 85 },
        releaseAtMovingEnd: 'to',
      },
    ],
    waterHazards: [
      {
        id: 'carrier-trench',
        rect: { x: 320, y: 380, w: 400, h: 220 },
        frozenByInteractionId: 'no-freeze-route',
      },
    ],
  },
  {
    id: 'level-22',
    name: 'LEVEL 22',
    subtitle: 'POLARITY HANDOFF',
    hint: 'Wake B1 while hot. On launch, cut left through the green coil—then reverse along the rail.',
    intent: {
      primaryRoute: 'START -> furnace heat -> ignition circuit -> dormant B1 -> steer left through airborne induction coil -> magnetic state replaces heat -> rail capture -> reverse right -> rail-end release -> receiving deck -> EXIT',
      launchJobs: [
        { bomb: 'B1', job: 'The heat-reactivated charge lifts the player through the elevated magnetic source and into the rail capture band.' },
      ],
      landingWindows: [
        { target: 'airborne induction coil and rail capture', kind: 'wide', description: 'The coil and capture band share a broad left-steered section of the B1 ascent.' },
        { target: 'right receiving deck', kind: 'wide', description: 'The deck sits directly beneath the static rail end.' },
      ],
      timingWindows: [
        { target: 'heat-powered B1', kind: 'commit', description: 'The ignition interval covers the first fuse and leaves time to settle against the marked launch stop.' },
        { target: 'magnetic traversal', kind: 'expiring', description: 'The airborne magnetic pickup and attachment comfortably cover one rightward rail crossing, not waiting.' },
      ],
      recovery: { kind: 'recoverable', description: 'An unpowered B1 remains dormant; missing the airborne handoff returns the left-steered arc to the launch floor for the repeating cycle.' },
      masteryShortcut: null,
      newConcept: 'None; dormant heat ignition, airborne state replacement, and bounded magnetic attachment form one dependent handoff.',
      recombinedSkills: ['heat acquisition', 'dormant charge reactivation', 'prepared blast timing', 'airborne reversal', 'state replacement', 'magnetic rail traversal'],
      targetFirstClearSeconds: { min: 120, max: 270 },
    },
    validation: {
      requiredBlastHits: ['B1'],
      requiredInteractions: ['handoff-ignition', 'handoff-rail'],
      requiredStates: ['heat', 'magnetic'],
      simplePoliciesMustFail: ['hold-left', 'neutral', 'hold-right'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 80, samples: 100, minimumClearRate: 0.8 },
      ],
    },
    start: { x: 72, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 320, h: 50 },
      { x: 286, y: 508, w: 14, h: 42 },
      { x: 760, y: 350, w: 182, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [
      {
        x: 273,
        y: 532,
        delay: -2.1,
        label: 'B1',
        reactivatedByInteractionId: 'handoff-ignition',
      },
    ],
    exit: { x: 840, y: 286, w: 102, h: 64 },
    pit: { x: 320, y: 350, w: 440, h: 250 },
    traversalStateSources: [
      {
        id: 'handoff-furnace',
        rect: { x: 80, y: 500, w: 76, h: 50 },
        grants: 'heat',
        durationSeconds: 5.5,
      },
      {
        id: 'airborne-induction-coil',
        rect: { x: 110, y: 230, w: 140, h: 160 },
        grants: 'magnetic',
        durationSeconds: 7,
      },
    ],
    traversalInteractions: [
      {
        id: 'handoff-ignition',
        rect: { x: 150, y: 500, w: 84, h: 50 },
        kind: 'reactivate-charge',
        accepts: ['heat'],
        activeSeconds: 4.5,
      },
      {
        id: 'handoff-rail',
        rect: { x: 110, y: 105, w: 230, h: 155 },
        kind: 'magnetic-attach',
        accepts: ['magnetic'],
        activeSeconds: 4,
        resultRect: { x: 130, y: 140, w: 680, h: 16 },
      },
    ],
    waterHazards: [
      {
        id: 'handoff-trench',
        rect: { x: 320, y: 350, w: 440, h: 250 },
        frozenByInteractionId: 'no-freeze-route',
      },
    ],
  },
  {
    id: 'level-23',
    name: 'LEVEL 23',
    subtitle: 'QUENCH DROP',
    hint: 'Ride to receiving. Drop through blue, freeze the catch, then take B2 left to inspection.',
    intent: {
      primaryRoute: 'START -> magnetic state -> B1 -> moving carrier -> receiving-end release -> coolant curtain replaces magnetic with cold -> freeze quench basin -> land on temporary ice -> B2 -> steer left -> inspection exit',
      launchJobs: [
        { bomb: 'B1', job: 'Lift the magnetized player into the moving carrier at its left dock.' },
        { bomb: 'B2', job: 'Relaunch from the cold-created basin landing toward the upper-left inspection deck.' },
      ],
      landingWindows: [
        { target: 'coolant curtain and quench basin', kind: 'wide', description: 'The carrier endpoint releases through a broad coolant curtain directly above the linked basin.' },
        { target: 'upper inspection line', kind: 'wide', description: 'B2 needs a familiar leftward steer, but the inspection line accepts carrier-position variation.' },
      ],
      timingWindows: [
        { target: 'carrier interception', kind: 'intercept', description: 'Prepared B1 meets the same readable left-dock carrier cycle established in Level 21.' },
        { target: 'temporary quench ice and B2', kind: 'expiring', description: 'The basin remains frozen through B2 preparation but thaws if the player waits instead of taking the launch.' },
      ],
      recovery: { kind: 'fatal', description: 'The start floor is safe; after carrier release, missing coolant or freeze contact enters the exposed quench water.' },
      masteryShortcut: null,
      newConcept: 'None; airborne magnetic-to-cold replacement prepares a landing that becomes the second launch site.',
      recombinedSkills: ['magnetic carrier interception', 'automatic endpoint release', 'airborne state replacement', 'timed water freezing', 'prepared B2 launch', 'leftward landing control'],
      targetFirstClearSeconds: { min: 150, max: 300 },
    },
    validation: {
      requiredBlastHits: ['B1', 'B2'],
      requiredInteractions: ['quench-carrier', 'quench-basin-freeze'],
      requiredStates: ['magnetic', 'cold'],
      simplePoliciesMustFail: ['hold-left', 'neutral', 'hold-right'],
      noisyHumanProfiles: [
        { jitterMilliseconds: 100, samples: 100, minimumClearRate: 0.8 },
      ],
    },
    start: { x: 72, y: 514 },
    platforms: [
      { x: 0, y: 550, w: 320, h: 50 },
      { x: 286, y: 508, w: 14, h: 42 },
      { x: 300, y: 90, w: 550, h: 22 },
      { x: 0, y: 0, w: 960, h: 18 },
      { x: 0, y: 0, w: 18, h: 600 },
      { x: 942, y: 0, w: 18, h: 600 },
    ],
    bombs: [
      { x: 273, y: 532, delay: -1.8, label: 'B1' },
      { x: 775, y: 402, delay: 4.3, label: 'B2', floating: true },
    ],
    exit: { x: 300, y: 90, w: 550, h: 64 },
    pit: { x: 320, y: 420, w: 622, h: 180 },
    traversalStateSources: [
      {
        id: 'quench-induction-coil',
        rect: { x: 80, y: 500, w: 82, h: 50 },
        grants: 'magnetic',
        durationSeconds: 10,
      },
      {
        id: 'quench-coolant-curtain',
        rect: { x: 690, y: 215, w: 175, h: 185 },
        grants: 'cold',
        durationSeconds: 4,
      },
    ],
    traversalInteractions: [
      {
        id: 'quench-carrier',
        rect: { x: 210, y: 130, w: 610, h: 120 },
        kind: 'magnetic-attach',
        accepts: ['magnetic'],
        activeSeconds: 5,
        movingResult: {
          fromX: 230,
          toX: 600,
          y: 155,
          w: 200,
          h: 16,
          speed: 85,
          phase: 5.2558823529,
        },
        movingCapturePadding: { horizontal: 20, above: 10, below: 85 },
        releaseAtMovingEnd: 'to',
      },
      {
        id: 'quench-basin-freeze',
        rect: { x: 660, y: 340, w: 220, h: 90 },
        kind: 'freeze-water',
        accepts: ['cold'],
        activeSeconds: 3,
        resultRect: { x: 640, y: 420, w: 240, h: 18 },
      },
    ],
    waterHazards: [
      {
        id: 'quench-basin',
        rect: { x: 640, y: 420, w: 240, h: 180 },
        frozenByInteractionId: 'quench-basin-freeze',
      },
    ],
  },
];
